#!/usr/bin/python
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime
from tkinter import *
import tkinter as tk
from tkinter import ttk
from PIL import Image, ImageTk
#import attendance2.py


scanner = Tk()
scanner.title('Face Scanner System')
scanner.geometry('700x700')
scanner['bg'] = '#5F9EF0'



b1 = Button(scanner, text='Scan a face', activebackground='#5F0AFF', padx=20, pady=3, bd='7')# command = attendance2.py)
b1.bind("<button-1>")#, facescan())
b1.pack(padx=10, pady=25)

b2 = Button(scanner, text='Exit', bd='7', padx=20, pady=3, command=scanner.destroy)
b2.pack()


im=Image.open("C:/PycharmProjects/homework/face.jpg")  #This is the correct location and spelling for my image location
photo=ImageTk.PhotoImage(im)
cv = tk.Canvas()
cv.pack(side='top', fill='both', expand='yes')
cv.create_image(10, 10, image=photo, anchor='nw')
# message_box = Message(screen,text)

scanner.mainloop()

